packages:
  - packages/*
  - '!playgrounds'
catalog:
  '@antfu/ni': ^0.23.0
  '@types/fs-extra': ^11.0.4
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-replace': ^5.0.7
  '@types/web-bluetooth': ^0.0.20
  '@typescript-eslint/utils': ^8.6.0
  '@types/node': ^22.5.5
  '@vitest/coverage-v8': ^2.1.1
  '@vitest/ui': ^2.1.1
  consola: ^3.2.3
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  js-yaml: ^4.1.0
  jsdom: ^25.0.0
  gray-matter: ^4.0.3
  vue-demi: '>=0.14.10'
  prettier: ^3.3.3
  esno: ^4.7.0
  '@vue/compiler-sfc': ^3.5.6
  vitest: ^2.1.1
  vite: ^5.4.6
  typescript: ^5.6.2
  yaml: ^2.6.0
  rimraf: ^6.0.1
  rollup: ^4.22.2
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  rollup-plugin-pure: ^0.2.1
  cross-env: ^7.0.3
  vue: ^3.5.6
  vue2: npm:vue@^2.7.14
  magic-string: ^0.30.11
  vite-plugin-pwa: ^0.20.5
